server:
  port: 9001
external:
  parser:
    url: http://172.16.101.142:10999/tde/usp/parse
dialoguePre: 入住时间？
dialogueBeh: 离店时间？
spring:
  elasticsearch:
    rest:
     uris: http://172.16.102.120:9200
     username: elastic
     password: zGGKZUG4D34gdwkyPCtXCd4KU56b2XtA

